server:
#  port: ${PORT:${SERVER_PORT:0}}
  port: ${PORT:50786}

idRandom: ${random.value}

spring:
  application:
    name: movie-service
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/netflix?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    generate-ddl: true
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672
#    addresses: localhost:5672
#    virtual-host: app_vhost
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: rabbit
    enabled: true
queue:
  movie:
    name: movieQueue
message: movieQueue up

management:
  endpoints:
    web:
      exposure:
        include: info
  info:
    env:
      enabled: true
  endpoint:
    info:
      enabled: true

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


