server:
  #  port: ${PORT:${SERVER_PORT:0}}
  port: ${PORT:50797}

idRandom: ${random.value}

spring:
  application:
    name: serie-service
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: netflix
      port: 27017

  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
#    addresses: localhost:5672
#    virtual-host: app_vhost
    username: guest
    password: guest
    host: localhost
    port: 5672
  zipkin:
    baseUrl: http://localhost:9411/
    sender:
      type: rabbit
    enabled: true

queue:
  seriecatalogo:
    name: seriecatalogQueue
message: seriecatalogo up

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/